AWSTemplateFormatVersion: 2010-09-09
Description: Secure ML environment template to create a complete and secure ML environment for demonstration purposes.

Parameters:
  StackPrefix:
    Description: The prefix to be used for named resources
    Type: String
    Default: endgame

Resources: 
  Network:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        StackPrefix: !Sub ${StackPrefix}-private-eks-vpc
      TemplateURL: network.yaml

  Principals:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        VPCId: !GetAtt Network.Outputs.VPCId
        StackPrefix: !Sub ${StackPrefix}
      TemplateURL: permissions.yaml

Outputs:
  VPCId:
    Description: Private EKS VPC ID
    Value: !GetAtt Network.Outputs.VPCId